name: Deploy LuxeDrive

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}     # Your Server IP
          username: ${{ secrets.SERVER_USER }} # Your Linux Username (e.g., ubuntu or midhun)
          key: ${{ secrets.SERVER_SSH_KEY }}   # Your Private SSH Key (.pem file content)
          script: |
            cd ~/luxe-drive
            git pull origin main
            cd frontend && npm install && npm run build
            cd ../backend && npm install
            pm2 restart all --update-env
            echo "🚀 Deployment Complete!"
